source 'https://rubygems.org'


gem 'rails', '4.2.1'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'

gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'pry'
gem 'bcrypt'

group :development, :test do
  gem 'byebug'
  gem 'rspec-rails'
  gem 'web-console', '~> 2.0'
  gem 'capybara'
  gem 'spring'
  gem 'better_errors'
  gem 'shoulda-matchers'
end
